version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            USER: '${USER}'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
#    rabbitmq:
#        image: rabbitmq:alpine
#        ports:
#            - '${RABBITMQ_NODE_HOST_PORT2}:5672'
#            - '${RABBITMQ_NODE_HOST_PORT1}:5671'
#        privileged: true
#        environment:
#            - RABBITMQ_DEFAULT_USER=guest
#            - RABBITMQ_DEFAULT_PASS=guest
#        hostname: laradock-rabbitmq
#        volumes:
#            - '${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq'
#            - './rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
#            - './rabbitmq/management_agent.disable_metrics_collector.conf:/etc/rabbitmq/conf.d/management_agent.disable_metrics_collector.conf'
#        networks:
#            - sail
    rabbitmq-management:
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASSWORD: guest
        hostname: rabbitmq
        volumes:
            - '${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq'
            - './rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
            - './rabbitmq/management_agent.disable_metrics_collector.conf:/etc/rabbitmq/conf.d/management_agent.disable_metrics_collector.conf'
        ports:
            - '${RABBITMQ_NODE_HOST_PORT2}:5672'
            - '${RABBITMQ_NODE_HOST_PORT1}:5671'
            - '${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672'
            - '${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
